apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ace-dashboard-instance
spec:
  destination:
    namespace: qa
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: ibm/us-east/toronto1/ocp-clusters/pre-prod-1/1-apps/inventory-management-svc-solution
    repoURL: https://github.com/hollisc/multi-tenancy-gitops.git
    targetRevision: demo1-ace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
