apiVersion: v2
name: mq-spring-app
description: A Helm chart for Kubernetes
type: application
version: 0.1.7
appVersion: 1.16.0
dependencies:
  - name: mq-spring-app
    version: 0.1.7
    repository: https://hollisc.github.io/gitops-testing/
