apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cntk-pipelines-tasks
spec:
  destination:
    namespace: tools
    server: https://kubernetes.default.svc
  project: services
  source:
    path: 2-services/instances/cloud-native-toolkit
    repoURL: https://github.com/csantanapr/multi-tenancy-gitops.git
    targetRevision: bringup
  syncPolicy:
    automated:
      prune: true
      selfHeal: true