apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
spec:
  destination:
    namespace: tools
    server: 'https://kubernetes.default.svc'
  project: services
  source:
    path: 2-services/active/instances/sonarqube
    repoURL: https://github.com/cloud-native-toolkit/multi-tenancy-gitops.git
    targetRevision: master
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
