# Default values for template-node-typescript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}
mq-spring-app:
  name: mq-spring-app
  replicaCount: 1

  configmap:
    CHANNEL: QA.APP.SVRCONN
    CONNECTION_NAME: qm-qa-ibm-mq.qa.svc.cluster.local(1414)
    QM: QUICKSTART
    QUEUE_NAME: QA.QUEUE.1
    APP_NAME: SPRINGBOOT-APP
