apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mq-spring-app-staging
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: ibm/us-east/toronto1/ocp-clusters/pre-prod-1/1-apps/staging/mq-spring-app
    repoURL: https://github.com/<github-org>/multi-tenancy-gitops.git
    targetRevision: demo-mq
    helm:
      valueFiles:
      - values.yaml
  syncPolicy: {}
