apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-cp4i-integration-base
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  project: services
  source:
    path: ibm/us-east/toronto1/ocp-clusters/pre-prod-1/2-services/operators/ibm-cp4i-integration-base
    repoURL: https://github.com/hollisc/multi-tenancy-gitops.git
    targetRevision: demo1-ace
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
