apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-mq-qa-instance
spec:
  destination:
    namespace: qa
    server: https://kubernetes.default.svc
  project: services
  source:
    path: ibm/us-east/toronto1/ocp-clusters/pre-prod-1/2-services/instances/ibm-mq/qa
    repoURL: https://github.com/hollisc/multi-tenancy-gitops.git
    targetRevision: demo2-mq
    helm:
      valueFiles:
      - values.yaml    
  syncPolicy: {}
