apiVersion: integration.ibm.com/v1beta1
kind: PlatformNavigator
metadata:
  name: integration-navigator
spec:
  license:
    accept: true
    license: L-RJON-BUVMQX
  mqDashboard: false
  version: 2020.4.1-eus
  replicas: 2
